---
ssh_kex:
  - sntrup761x25519-sha512@openssh.com
  - curve25519-sha256@libssh.org
  - curve25519-sha256
  - ecdh-sha2-nistp521
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp256
  - diffie-hellman-group18-sha512
  - diffie-hellman-group16-sha512
  - diffie-hellman-group-exchange-sha256